#!/bin/bash
# Materialize sibling-repo content under <workdir>/.siblings/<owner>/<repo>.
#
# Why: lib/search-roots.sh used to write absolute host paths (e.g.
# /home/odio/Hacking/plow-content) into .codex-scratch/search-roots.md,
# and specialists cited those paths back when they found a hit — leaking
# the reviewer's filesystem layout into public PR comments. Materializing
# siblings into the workdir gives specialists a workdir-relative grep
# target (.siblings/<owner>/<repo>/...) and a citation form
# (<owner>/<repo>/<rel-path>) that's safe to post.
#
# Three security-relevant design points:
#
# 1. Whitelist-gating happens UPSTREAM, in stage_search_roots. The
#    caller passes the explicit list of `included` slugs (those
#    whitelisted in SOURCE_PATHS AND with checkouts present on disk
#    AND a git repo). This helper does NOT iterate over SOURCE_PATHS
#    itself. Otherwise we'd materialize entries for siblings whose
#    checkouts are absent — confusing specialists.
#
# 2. The PR's own checkout might already contain `.siblings/` with a
#    committed symlink redirecting `.siblings/<owner>` (or any
#    intermediate) outside the workdir, e.g. to ~/.ssh/. If we just
#    `mkdir -p` and write through that, our writes follow the redirect.
#    So we wipe the entire `.siblings/` subtree first and create a
#    fresh empty directory we own.
#
# 3. The materialized tree exposes ONLY tracked files (`git ls-files`),
#    not the raw checkout root. Per-machine artifacts that aren't part
#    of the sibling's source — `.git/`, `.venv/`, `node_modules/`,
#    `__pycache__/`, lockfile-generated byproducts — never appear, so
#    a specialist grep cannot pull bytes from them and quote them in
#    public review output. Caught on cncorp/plow#567 review rounds 1-4.
#    The materialized files are REAL FILES (cp), not symlinks, because
#    `grep -r` doesn't follow symlinks during recursive traversal —
#    per-file symlinks would silently produce zero hits on every
#    consumer/dead-code grep, defeating the search-roots contract
#    while reporting "full" coverage. Catching that here keeps the
#    contract single-owner: any consumer can grep the slug dir with
#    any flags and get the right answer. (cncorp/plow#37 review 1
#    bot finding 1 — Bug-Class-Recurrence.)

# materialize_sibling_symlinks <workdir> <source_paths_var_name> <included_slug>...
#
#   workdir            absolute path to the per-PR workdir
#   source_paths_var   name of the SOURCE_PATHS associative array
#                      (passed by name; bash declare -n)
#   included_slug...   variadic list of "<owner>/<repo>" entries that
#                      stage_search_roots classified as `included`
#                      (whitelisted + checkout-present + git repo).
#                      NOTHING outside this list gets materialized.
#                      Empty list = empty .siblings/.
#
# Idempotent: safe to call multiple times in the same workdir.
materialize_sibling_symlinks() {
    local workdir="$1"
    local -n _src_paths="$2"
    shift 2
    local slug src target

    # Wipe whatever .siblings/ shipped in the PR checkout. `rm -rf`
    # removes symlinks as symlinks (it does not follow them as long as
    # the path doesn't end with a trailing slash), so a committed
    # `.siblings -> /etc/` redirect is unlinked rather than recursed
    # into. After this, the parent directory is one we just created.
    rm -rf "$workdir/.siblings"
    mkdir -p "$workdir/.siblings"

    local rel
    for slug in "$@"; do
        src="${_src_paths[$slug]:-}"
        [ -z "$src" ] && continue
        [ -d "$src" ] || continue
        target="$workdir/.siblings/$slug"
        # The owner-level parent (e.g. .siblings/cncorp) was just
        # mkdir-ed inside our freshly-created .siblings/ so there's no
        # symlink to follow.
        mkdir -p "$target"
        # Per-file COPIES of each tracked file. Respects .gitignore —
        # `.git/`, `.venv/`, `node_modules/`, `__pycache__/` etc.
        # cannot leak into specialist greps. Copies (not symlinks)
        # because `grep -r` skips symlinks during recursive traversal;
        # using symlinks here would silently zero out every consumer
        # and dead-code grep across siblings. If `git ls-files` fails
        # (caller passed a slug whose source isn't a git repo,
        # corrupt objects), the loop simply yields no entries and the
        # slug ends up with an empty .siblings/<slug>/ — but the
        # caller (stage_search_roots) is supposed to have classified
        # those as `missing` upstream so they never reach this loop.
        #
        # Tracked symlinks (mode 120000) are skipped: `cp` follows
        # symlinks by default, so a sibling tracking
        # `leak -> ~/.ssh/id_rsa` (or any path outside the source tree)
        # would copy the target bytes into .siblings/<slug>/leak
        # where specialists could quote them. Skipping is simpler than
        # materializing-symlink-blobs-as-text and avoids a future
        # consumer assuming the file content is real source code.
        # Caught on PR #37 review 2 finding 1.
        while IFS= read -r -d '' rel; do
            [ -L "$src/$rel" ] && continue
            mkdir -p "$target/$(dirname "$rel")"
            cp -- "$src/$rel" "$target/$rel"
        done < <(cd "$src" && git ls-files -z 2>/dev/null)
    done
}
