# Shared loader for the tracked-repos manifest.
#
# Single seam between the manifest file (repos.conf) and every consumer
# (review.sh, re-request-poller.sh, learn-from-replies.sh,
# approve-from-replies.sh, lib/review-one-pr.sh). Adding a new consumer
# means sourcing this file — not duplicating the source-twice-then-assert
# bootstrap that lived inline in each script before.
#
# Caller contract:
#   - $STATE_DIR must be set before sourcing.
#   - Source at FILE SCOPE, not inside a function. `declare -A` inside a
#     function creates locals (even with `-g`-pre-declared globals as
#     intended targets), and repos.conf uses bare `declare -A KID_PATHS=…`
#     so its assignment must land in the global scope.
#
# Pre-declares REPOS and KID_PATHS as empty so accesses stay safe under
# `set -u` even when repos.conf is absent (e.g. narrow test sandboxes).
# Consumers that REQUIRE a non-empty REPOS assert it themselves after
# sourcing — the worker (lib/review-one-pr.sh) doesn't, because it only
# needs KID_PATHS for prior-art lookup and works fine when repos.conf
# is missing for a particular kid.

declare -a REPOS=()
declare -A KID_PATHS=()
declare -A SOURCE_PATHS=()
# ORGS — GitHub orgs reviewed in FULL: every non-archived open PR in the org
# is eligible, discovered via one batched `search(user:<org> …)` per owner per
# tick (NOT a per-repo fan-out — see lib/pr-enumerate.sh). A newly-created repo
# in an ORGS owner is reviewed the moment it has a PR, no manifest edit. This
# is the whole-org coverage the per-repo REPOS list can only approximate (and
# silently drifts from). Partial orgs — review only specific repos, e.g.
# cncorp/plow — stay OUT of ORGS and list those repos in REPOS instead.
# Pre-declared empty so consumers load cleanly under `set -u` when unset.
declare -a ORGS=()
# Source order: config.env (ops knobs) → repos.conf (manual) →
# repos.conf.auto (tool-owned, regenerated by org-sync.sh — only
# emits `REPOS+=(...)`; KID_PATHS values are convention-defaulted
# below from $KWR_CLONE_ROOT, so the manifest never stores stale
# path strings). `if/then/fi` is errexit-exempt; `[ -f X ] && . X`
# would not be.
# CONFIG_ENV_FILE lets the container deployment keep config.env (which holds
# `export GH_TOKEN=…`) on a root-only path instead of the shared volume, so the
# unprivileged reviewer-test user that runs `just test` can't read the token
# file. Defaults to $STATE_DIR/config.env (unchanged for the host/systemd path).
CONFIG_ENV_FILE="${CONFIG_ENV_FILE:-${STATE_DIR}/config.env}"
if [ -f "$CONFIG_ENV_FILE" ];             then . "$CONFIG_ENV_FILE"; fi
if [ -f "${STATE_DIR}/repos.conf" ];      then . "${STATE_DIR}/repos.conf"; fi

# Snapshot operator-set KID_PATHS keys BEFORE sourcing the auto
# manifest. A pre-refactor auto manifest may still contain
# `KID_PATHS["..."]="${KID_PATHS["..."]:-$HOME/Hacking/<name>}"`
# entries from org-sync runs before this loader convention-defaulted
# the auto paths. Those legacy KID_PATHS values are NOT a manual
# override — they're stale state. Drop them after sourcing the auto
# file so the convention-default loop below refills them from
# $KWR_CLONE_ROOT. After org-sync regenerates the manifest (no
# KID_PATHS emission), this filter is a no-op but stays load-bearing
# on the first install after upgrade and against operator misuse of
# the "do not edit" auto file.
declare -A _MANUAL_KID_KEYS=()
for _k in "${!KID_PATHS[@]}"; do _MANUAL_KID_KEYS[$_k]=1; done

if [ -f "${STATE_DIR}/repos.conf.auto" ]; then . "${STATE_DIR}/repos.conf.auto"; fi

for _k in "${!KID_PATHS[@]}"; do
    [ -n "${_MANUAL_KID_KEYS[$_k]:-}" ] && continue
    unset "KID_PATHS[$_k]"
done
unset _MANUAL_KID_KEYS _k

# Dedup REPOS preserving order. Bash indexed arrays have no
# "append-only-if-missing" primitive, so the auto file's REPOS+=("...")
# is unconditional. During the operator-promotion window (manual entry
# added before the next sync prunes the auto twin), REPOS would carry
# the slug twice and consumers iterating it would double-process.
if [ "${#REPOS[@]}" -gt 0 ]; then
    mapfile -t REPOS < <(printf '%s\n' "${REPOS[@]}" | awk '!seen[$0]++')
fi

# Startup guard for the PR-enumeration entry scripts (review.sh,
# approve-from-replies.sh, re-request-poller.sh): they enumerate via
# enumerate_open_prs, which covers whole ORGS plus per-repo REPOS, so a
# non-empty REPOS OR a non-empty ORGS is a satisfiable config. Emits a FATAL
# line and exits when neither is set — one copy of the message, called by all
# three (learn-from-replies / specialist-bakeoff do per-repo walks and use the
# REPOS-only require_repos guard below instead).
require_tracked_targets() {
    [ "${#REPOS[@]}" -ge 1 ] || [ "${#ORGS[@]}" -ge 1 ] || {
        echo "FATAL: no tracked targets — populate $STATE_DIR/repos.conf with REPOS and/or ORGS (or set them in config.env)" >&2
        exit 1
    }
}

# Guard for the per-repo calibration timers (learn-from-replies.sh,
# specialist-bakeoff.sh): these walk REPOS only — whole-org ORGS coverage is
# the review path's, not theirs. An empty REPOS is a legitimate opt-out
# ("nothing to calibrate"), NOT an error — so exit 0 cleanly (vs a FATAL that
# would leave the timers as permanently-failed units on an ORGS-only manifest).
require_repos() {
    [ "${#REPOS[@]}" -ge 1 ] || {
        echo "no REPOS configured — per-repo calibration scans REPOS only (ORGS covers the review path, not this); nothing to do this tick" >&2
        exit 0
    }
}

# Auto-clone root for org-sync-discovered repos. Single source of truth
# for the convention path — org-sync.sh's clone dest, install.sh's
# systemd template substitution, the org-sync systemd unit's
# ReadWritePaths, and the KID_PATHS convention-default below all
# derive from this. Setting AFTER the manifest sources means a stale
# manifest can't clobber the constant; override via shell env
# (`export KWR_CLONE_ROOT=...`) or config.env if needed.
KWR_CLONE_ROOT="${KWR_CLONE_ROOT:-$HOME/services/kwr-repos}"

# Convention-default KID_PATHS for REPOS that lack a manual override.
# Manual KID_PATHS entries in repos.conf are sourced first (above) so
# they win on collision — this loop only fills the unset keys with the
# convention path. Auto-managed repos no longer embed their KID_PATHS
# value in repos.conf.auto; the convention is the source of truth,
# computed exactly once here.
for _full in "${REPOS[@]}"; do
    [ -n "${KID_PATHS[$_full]:-}" ] && continue
    KID_PATHS[$_full]="$KWR_CLONE_ROOT/${_full#*/}"
done
unset _full

# Single owner of the post-config TMPDIR policy. pr-reviewer.service
# combines PrivateTmp=yes (sandbox) with KillMode=process (workers
# survive orchestrator exit); the unit-private /tmp tears down when the
# unit deactivates a few seconds later, so any detached worker doing
# `mktemp` in /tmp lands in a dead mount namespace and the call fails
# with `'/tmp/tmp.XXXXXXXXXX': No such file or directory`. STATE_DIR
# lives outside the private mount and is in the unit's ReadWritePaths.
#
# Pinning unconditionally — and HERE, after config.env may have set its
# own TMPDIR — makes $STATE_DIR/tmp policy: every consumer that sources
# this loader (review.sh orchestrator + lib/review-one-pr.sh worker +
# all -from-replies / -poller / -refresh siblings) gets the same pin
# without each script needing its own order-sensitive copy. This is
# Bug-Class-Recurrence territory — the prior per-script duplication
# made each new entrypoint a fresh chance to regress the invariant.
export TMPDIR="$STATE_DIR/tmp"
mkdir -p "$TMPDIR"
