# Shared loader for the tracked-repos manifest.
#
# Single seam between the manifest file (repos.conf) and every consumer
# (review.sh, re-request-poller.sh, learn-from-replies.sh,
# approve-from-replies.sh, lib/review-one-pr.sh). Adding a new consumer
# means sourcing this file — not duplicating the source-twice-then-assert
# bootstrap that lived inline in each script before.
#
# Caller contract:
#   - $STATE_DIR must be set before sourcing.
#   - Source at FILE SCOPE, not inside a function. `declare -A` inside a
#     function creates locals (even with `-g`-pre-declared globals as
#     intended targets), and repos.conf uses bare `declare -A KID_PATHS=…`
#     so its assignment must land in the global scope.
#
# Pre-declares REPOS and KID_PATHS as empty so accesses stay safe under
# `set -u` even when repos.conf is absent (e.g. narrow test sandboxes).
# Consumers that REQUIRE a non-empty REPOS assert it themselves after
# sourcing — the worker (lib/review-one-pr.sh) doesn't, because it only
# needs KID_PATHS for prior-art lookup and works fine when repos.conf
# is missing for a particular kid.

declare -a REPOS=()
declare -A KID_PATHS=()
declare -A SOURCE_PATHS=()
# ORGS — optional GitHub orgs that org-sync.sh discovers + folds into
# REPOS hourly. Pre-declared empty so consumers that don't enable
# org-sync still load cleanly under `set -u`.
declare -a ORGS=()
# Source order: config.env (ops knobs) → repos.conf (manual) →
# repos.conf.auto (tool-owned, regenerated by org-sync.sh — only
# emits `REPOS+=(...)`; KID_PATHS values are convention-defaulted
# below from $KWR_CLONE_ROOT, so the manifest never stores stale
# path strings). `if/then/fi` is errexit-exempt; `[ -f X ] && . X`
# would not be.
if [ -f "${STATE_DIR}/config.env" ];      then . "${STATE_DIR}/config.env"; fi
if [ -f "${STATE_DIR}/repos.conf" ];      then . "${STATE_DIR}/repos.conf"; fi
if [ -f "${STATE_DIR}/repos.conf.auto" ]; then . "${STATE_DIR}/repos.conf.auto"; fi

# Dedup REPOS preserving order. Bash indexed arrays have no
# "append-only-if-missing" primitive, so the auto file's REPOS+=("...")
# is unconditional. During the operator-promotion window (manual entry
# added before the next sync prunes the auto twin), REPOS would carry
# the slug twice and consumers iterating it would double-process.
if [ "${#REPOS[@]}" -gt 0 ]; then
    mapfile -t REPOS < <(printf '%s\n' "${REPOS[@]}" | awk '!seen[$0]++')
fi

# Auto-clone root for org-sync-discovered repos. Single source of truth
# for the convention path — org-sync.sh's clone dest, install.sh's
# systemd template substitution, the org-sync systemd unit's
# ReadWritePaths, and the KID_PATHS convention-default below all
# derive from this. Setting AFTER the manifest sources means a stale
# manifest can't clobber the constant; override via shell env
# (`export KWR_CLONE_ROOT=...`) or config.env if needed.
KWR_CLONE_ROOT="${KWR_CLONE_ROOT:-$HOME/services/kwr-repos}"

# Convention-default KID_PATHS for REPOS that lack a manual override.
# Manual KID_PATHS entries in repos.conf are sourced first (above) so
# they win on collision — this loop only fills the unset keys with the
# convention path. Auto-managed repos no longer embed their KID_PATHS
# value in repos.conf.auto; the convention is the source of truth,
# computed exactly once here.
for _full in "${REPOS[@]}"; do
    [ -n "${KID_PATHS[$_full]:-}" ] && continue
    KID_PATHS[$_full]="$KWR_CLONE_ROOT/${_full#*/}"
done
unset _full

# Single owner of the post-config TMPDIR policy. pr-reviewer.service
# combines PrivateTmp=yes (sandbox) with KillMode=process (workers
# survive orchestrator exit); the unit-private /tmp tears down when the
# unit deactivates a few seconds later, so any detached worker doing
# `mktemp` in /tmp lands in a dead mount namespace and the call fails
# with `'/tmp/tmp.XXXXXXXXXX': No such file or directory`. STATE_DIR
# lives outside the private mount and is in the unit's ReadWritePaths.
#
# Pinning unconditionally — and HERE, after config.env may have set its
# own TMPDIR — makes $STATE_DIR/tmp policy: every consumer that sources
# this loader (review.sh orchestrator + lib/review-one-pr.sh worker +
# all -from-replies / -poller / -refresh siblings) gets the same pin
# without each script needing its own order-sensitive copy. This is
# Bug-Class-Recurrence territory — the prior per-script duplication
# made each new entrypoint a fresh chance to regress the invariant.
export TMPDIR="$STATE_DIR/tmp"
mkdir -p "$TMPDIR"
