#!/bin/bash
# Smoke for the consolidated top-of-comment disclosure helper:
#   prepend_review_header COMMENT_BODY SCOPE REVIEWED_SHA CURRENT_HEAD TESTS_RAN
# (and the pure helper compute_review_scope it depends on).
#
# Replaces the two prior smokes (stale-head-smoke.sh + review-scope-
# smoke.sh) that fenced the two helpers stacked into separate
# blockquotes. The current contract is one concise blockquote with three
# signals: scope text always present, stale-head one-sentence suffix
# appended only when CURRENT_HEAD differs from REVIEWED_SHA, and
# tests-not-run suffix appended only when TESTS_RAN="false". All
# signals visible at one vertical glance.
#
# Coverage matrix:
#
#   scope = first | whole | incremental:<sha> | fallback:<sha>
#   × stale-head = matched | differs | empty (gh-failure)
#   = 12 combinations (TESTS_RAN=true), all fenced below.
#
# Plus a separate axis for TESTS_RAN=false (no justfile / recipe broken):
#   - tests-not-run + matched-shas → tests suffix only
#   - tests-not-run + stale-shas   → stale + tests suffixes both present
#   - all four scope variants exercised at TESTS_RAN=false
#
# Plus:
#   - unknown scope → fail-fast (return non-zero, stderr diagnostic).
#     scope is internally generated by compute_review_scope; an unknown
#     value means an invariant violation. Per CLAUDE.md / feedback_fail_hard,
#     the helper must NOT silently omit the disclosure (that would let a
#     regression ship a header-less review).
#   - marker stays on first line (orchestrator's self-trigger filter
#     depends on it).
#   - original body content (intent line + finding) preserved.
#   - compute_review_scope direct mapping (5 worker-seam scenarios) so
#     a regression at the worker layer trips even if the formatter is fine.
#
# Hermetic — sources lib/run-dir.sh and invokes helpers with explicit
# args; no closure state needed.

set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=../run-dir.sh
. "$PROJECT_ROOT/lib/run-dir.sh"

MARKER='<!-- knightwatch-reviewer:auto-post -->'
BODY=$(printf '%s\n_intent line_\n\n**Overview** — text\n\n**Findings**\n1. [medium] something' "$MARKER")

SHA_OLD="abc1234567"
SHA_NEW="def9876543"

assert_marker_first() {
    local result="$1" scenario="$2"
    local first
    first=$(printf '%s' "$result" | head -1)
    if [ "$first" != "$MARKER" ]; then
        echo "FAIL: $scenario — first line is no longer the auto-post marker"
        echo "  got: $first"
        exit 1
    fi
}

assert_body_preserved() {
    local result="$1" scenario="$2"
    if ! printf '%s' "$result" | grep -q "_intent line_"; then
        echo "FAIL: $scenario — original intent line lost"
        echo "$result"
        exit 1
    fi
    if ! printf '%s' "$result" | grep -q "1\. \[medium\] something"; then
        echo "FAIL: $scenario — original finding text lost"
        echo "$result"
        exit 1
    fi
}

assert_contains() {
    local result="$1" needle="$2" scenario="$3"
    if ! printf '%s' "$result" | grep -qF "$needle"; then
        echo "FAIL: $scenario — expected to contain: $needle"
        echo "  got:"
        echo "$result"
        exit 1
    fi
}

assert_no_stale_suffix() {
    local result="$1" scenario="$2"
    if printf '%s' "$result" | grep -q "Stale:"; then
        echo "FAIL: $scenario — unexpected stale suffix in header"
        echo "$result"
        exit 1
    fi
}

assert_no_tests_suffix() {
    local result="$1" scenario="$2"
    if printf '%s' "$result" | grep -q "Tests not run"; then
        echo "FAIL: $scenario — unexpected tests-not-run suffix in header"
        echo "$result"
        exit 1
    fi
}

assert_one_blockquote() {
    # The whole point of consolidating: one blockquote line, not two
    # stacked ones. Count lines starting with `> ` — must be exactly 1.
    local result="$1" scenario="$2" count
    count=$(printf '%s\n' "$result" | grep -c '^> ')
    if [ "$count" -ne 1 ]; then
        echo "FAIL: $scenario — expected exactly 1 blockquote line, got $count"
        echo "$result"
        exit 1
    fi
}

# ===== Scope variants × stale=matched (no suffix) =====
echo "  scope=first  + matched-shas → header has scope only..."
result=$(prepend_review_header "$BODY" "first" "$SHA_OLD" "$SHA_OLD" "true")
assert_marker_first "$result" "first/matched"
assert_body_preserved "$result" "first/matched"
assert_one_blockquote "$result" "first/matched"
assert_contains "$result" "First review of this PR." "first/matched scope text"
assert_no_stale_suffix "$result" "first/matched"
assert_no_tests_suffix "$result" "first/matched"

echo "  scope=whole  + matched-shas → header has scope only..."
result=$(prepend_review_header "$BODY" "whole" "$SHA_OLD" "$SHA_OLD" "true")
assert_marker_first "$result" "whole/matched"
assert_body_preserved "$result" "whole/matched"
assert_one_blockquote "$result" "whole/matched"
assert_contains "$result" "Whole-PR re-review" "whole/matched scope text"
assert_contains "$result" '`/srosro-review`' "whole/matched cites trigger command"
assert_contains "$result" "from scratch" "whole/matched discloses no-prior-review consultation"
assert_no_stale_suffix "$result" "whole/matched"

echo "  scope=incremental:<sha> + matched-shas → header cites prior SHA..."
result=$(prepend_review_header "$BODY" "incremental:$SHA_OLD" "$SHA_OLD" "$SHA_OLD" "true")
assert_marker_first "$result" "incremental/matched"
assert_body_preserved "$result" "incremental/matched"
assert_one_blockquote "$result" "incremental/matched"
assert_contains "$result" 'Re-review of changes since `abc1234`' "incremental/matched scope text"
assert_no_stale_suffix "$result" "incremental/matched"

echo "  scope=fallback:<sha> + matched-shas → header discloses force-push/rebase..."
result=$(prepend_review_header "$BODY" "fallback:$SHA_OLD" "$SHA_OLD" "$SHA_OLD" "true")
assert_marker_first "$result" "fallback/matched"
assert_body_preserved "$result" "fallback/matched"
assert_one_blockquote "$result" "fallback/matched"
assert_contains "$result" '`abc1234`' "fallback/matched cites prior SHA"
assert_contains "$result" "force-push/rebase" "fallback/matched names cause"
assert_contains "$result" "evaluated full PR" "fallback/matched discloses full-PR scope"
assert_no_stale_suffix "$result" "fallback/matched"

# ===== Scope variants × stale=differs (suffix appended) =====
echo "  scope=first  + differing-shas → header has scope + stale suffix on same line..."
result=$(prepend_review_header "$BODY" "first" "$SHA_OLD" "$SHA_NEW" "true")
assert_marker_first "$result" "first/stale"
assert_body_preserved "$result" "first/stale"
assert_one_blockquote "$result" "first/stale"
assert_contains "$result" "First review" "first/stale scope text"
assert_contains "$result" 'Stale: head moved from `abc1234` to `def9876`' "first/stale suffix cites both SHAs"
# Wording-fence: must NOT regress to the pre-consolidation copy that
# claimed auto-recovery on the next orchestrator tick (real cadence is
# STABLE_SECS=3600 — non-forced re-reviews wait an hour).
if printf '%s' "$result" | grep -q "next orchestrator tick"; then
    echo "FAIL: first/stale — re-introduced misleading 'next orchestrator tick' auto-recovery promise"
    exit 1
fi
assert_contains "$result" "see commands below" "first/stale points to footer commands"
# Wording-fence: stale suffix must NOT name a specific slash-command —
# defer to the footer (single source of truth for usage).
if printf '%s' "$result" | grep -q "/srosro-update-review"; then
    # The whole-scope text legitimately cites /srosro-review, but the
    # stale suffix in scope=first should not duplicate any slash-command.
    echo "FAIL: first/stale — stale suffix duplicates a slash-command name (should defer to footer)"
    exit 1
fi

echo "  scope=incremental:<sha> + differing-shas → both signals on one line..."
result=$(prepend_review_header "$BODY" "incremental:$SHA_OLD" "$SHA_OLD" "$SHA_NEW" "true")
assert_marker_first "$result" "incremental/stale"
assert_one_blockquote "$result" "incremental/stale"
assert_contains "$result" "Re-review of changes since" "incremental/stale scope text"
assert_contains "$result" "Stale: head moved" "incremental/stale suffix"
assert_contains "$result" '`def9876`' "incremental/stale cites new head"

echo "  scope=whole + differing-shas → scope + stale on one line..."
result=$(prepend_review_header "$BODY" "whole" "$SHA_OLD" "$SHA_NEW" "true")
assert_one_blockquote "$result" "whole/stale"
assert_contains "$result" "Whole-PR re-review" "whole/stale scope text"
assert_contains "$result" "Stale: head moved" "whole/stale suffix"

echo "  scope=fallback:<sha> + differing-shas → scope + stale on one line..."
result=$(prepend_review_header "$BODY" "fallback:$SHA_OLD" "$SHA_OLD" "$SHA_NEW" "true")
assert_one_blockquote "$result" "fallback/stale"
assert_contains "$result" "force-push/rebase" "fallback/stale scope text"
assert_contains "$result" "Stale: head moved" "fallback/stale suffix"

# ===== Scope variants × stale=empty CURRENT_HEAD (gh-failure path) =====
# Best-effort fetch fails → no warning. Identical to matched.
echo "  scope=incremental + empty CURRENT_HEAD (gh-failure) → no stale suffix..."
result=$(prepend_review_header "$BODY" "incremental:$SHA_OLD" "$SHA_OLD" "" "true")
assert_marker_first "$result" "incremental/gh-fail"
assert_one_blockquote "$result" "incremental/gh-fail"
assert_contains "$result" "Re-review of changes since" "incremental/gh-fail scope text"
assert_no_stale_suffix "$result" "incremental/gh-fail"

# ===== Unknown scope → fail-fast =====
echo "  scope=bogus → fail-fast (non-zero exit + stderr diagnostic)..."
result=$(prepend_review_header "$BODY" "bogus" "$SHA_OLD" "$SHA_OLD" "true" 2>/dev/null)
if [ "$?" -eq 0 ]; then
    echo "FAIL: bogus scope — function returned 0 (silent degrade); should exit non-zero per CLAUDE.md fail-fast"
    exit 1
fi
err=$(prepend_review_header "$BODY" "bogus" "$SHA_OLD" "$SHA_OLD" "true" 2>&1 >/dev/null)
if ! printf '%s' "$err" | grep -q "unknown scope"; then
    echo "FAIL: bogus scope — stderr diagnostic missing 'unknown scope' phrasing; got: $err"
    exit 1
fi

# ===== TESTS_RAN=false (worker couldn't run `just test`) =====
# When the bot can't run the project's tests (no justfile, or recipe
# command-not-found inside justfile), specialists review the diff alone.
# The header must disclose that — otherwise the reader assumes "no test
# failures flagged" means tests ran and passed.
echo "  scope=first + tests-not-run → tests suffix appended..."
result=$(prepend_review_header "$BODY" "first" "$SHA_OLD" "$SHA_OLD" "false")
assert_marker_first "$result" "first/no-tests"
assert_body_preserved "$result" "first/no-tests"
assert_one_blockquote "$result" "first/no-tests"
assert_contains "$result" "First review" "first/no-tests scope text"
assert_no_stale_suffix "$result" "first/no-tests"
assert_contains "$result" "🧪 Tests not run" "first/no-tests tests suffix"
assert_contains "$result" "diff alone" "first/no-tests names what review is based on"
assert_contains "$result" "test-results section" "first/no-tests points reader to details"

echo "  scope=incremental + tests-not-run → tests suffix on one line with scope..."
result=$(prepend_review_header "$BODY" "incremental:$SHA_OLD" "$SHA_OLD" "$SHA_OLD" "false")
assert_one_blockquote "$result" "incremental/no-tests"
assert_contains "$result" "Re-review of changes since" "incremental/no-tests scope text"
assert_contains "$result" "Tests not run" "incremental/no-tests tests suffix"
assert_no_stale_suffix "$result" "incremental/no-tests"

echo "  scope=whole + tests-not-run → both signals..."
result=$(prepend_review_header "$BODY" "whole" "$SHA_OLD" "$SHA_OLD" "false")
assert_one_blockquote "$result" "whole/no-tests"
assert_contains "$result" "Whole-PR re-review" "whole/no-tests scope text"
assert_contains "$result" "Tests not run" "whole/no-tests tests suffix"

echo "  scope=fallback + tests-not-run → both signals..."
result=$(prepend_review_header "$BODY" "fallback:$SHA_OLD" "$SHA_OLD" "$SHA_OLD" "false")
assert_one_blockquote "$result" "fallback/no-tests"
assert_contains "$result" "force-push/rebase" "fallback/no-tests scope text"
assert_contains "$result" "Tests not run" "fallback/no-tests tests suffix"

# All three signals at once: scope + stale + tests-not-run on a single
# blockquote line. Worst-case header — make sure it doesn't fork into
# multiple lines and all three pieces are present.
echo "  scope=incremental + stale + tests-not-run → all three signals on one line..."
result=$(prepend_review_header "$BODY" "incremental:$SHA_OLD" "$SHA_OLD" "$SHA_NEW" "false")
assert_marker_first "$result" "all-three"
assert_body_preserved "$result" "all-three"
assert_one_blockquote "$result" "all-three"
assert_contains "$result" "Re-review of changes since" "all-three scope text"
assert_contains "$result" "Stale: head moved" "all-three stale suffix"
assert_contains "$result" "Tests not run" "all-three tests suffix"

# Ordering fence: scope first, stale second, tests third. If a future
# refactor swaps the order, the assertion below trips. Order matters
# for readability — scope sets the frame, stale-head warns about
# freshness, tests-not-run is the smallest scope-of-disclosure.
result_line=$(printf '%s\n' "$result" | grep '^> ')
scope_pos=$(printf '%s' "$result_line" | grep -bo 'Re-review of changes since' | head -1 | cut -d: -f1)
stale_pos=$(printf '%s' "$result_line" | grep -bo 'Stale: head moved' | head -1 | cut -d: -f1)
tests_pos=$(printf '%s' "$result_line" | grep -bo 'Tests not run' | head -1 | cut -d: -f1)
if ! { [ "$scope_pos" -lt "$stale_pos" ] && [ "$stale_pos" -lt "$tests_pos" ]; }; then
    echo "FAIL: all-three — suffix order regressed (scope=$scope_pos, stale=$stale_pos, tests=$tests_pos); expected scope < stale < tests"
    echo "$result_line"
    exit 1
fi

# TESTS_RAN="" (empty) and "anything-else" must NOT add the suffix —
# only literal "false" triggers it. Defensive: a future bug that
# stringifies a bool as "0" / "False" / "no" must not silently start
# warning on every review.
echo "  TESTS_RAN='' (empty) → no tests suffix (only literal 'false' triggers)..."
result=$(prepend_review_header "$BODY" "first" "$SHA_OLD" "$SHA_OLD" "")
assert_no_tests_suffix "$result" "tests_ran=empty"
echo "  TESTS_RAN='no' (non-'false' truthy variant) → no tests suffix..."
result=$(prepend_review_header "$BODY" "first" "$SHA_OLD" "$SHA_OLD" "no")
assert_no_tests_suffix "$result" "tests_ran=no"

# ===== compute_review_scope (worker seam) =====
# A second drift surface — flagged in PR #22's bot review as the recurring
# class — is the worker computation itself: if the case that flips
# USED_FALLBACK or the precedence between FORCE_WHOLE_PR / KNOWN_SHA
# regresses, the formatter still produces a valid header but for the
# wrong scope. Pin the worker-seam mapping directly.
assert_scope() {
    local got="$1" want="$2" desc="$3"
    if [ "$got" != "$want" ]; then
        echo "FAIL: compute_review_scope — $desc: expected '$want', got '$got'"
        exit 1
    fi
}

echo "  compute_review_scope: force=true + no sha → 'whole'..."
assert_scope "$(compute_review_scope true "" false)" "whole" "force-only"

echo "  compute_review_scope: force=true + sha + fallback=true → 'whole' (force precedence)..."
# Precedence regression-fence: /srosro-review explicitly asks for whole-PR
# and must NOT be downgraded to incremental or fallback even when
# KNOWN_SHA is set or the SHA was evicted.
assert_scope "$(compute_review_scope true "abc1234567" true)" "whole" "force takes precedence over sha+fallback"

echo "  compute_review_scope: no force + no sha → 'first'..."
assert_scope "$(compute_review_scope false "" false)" "first" "no-sha → first"

echo "  compute_review_scope: no force + sha + fallback=false → 'incremental:<sha>'..."
assert_scope "$(compute_review_scope false "abc1234567" false)" "incremental:abc1234567" "incremental path"

echo "  compute_review_scope: no force + sha + fallback=true → 'fallback:<sha>'..."
# The original silent-fallback bug: USED_FALLBACK=true previously got
# framed as incremental in the banner. Pin against regression.
assert_scope "$(compute_review_scope false "abc1234567" true)" "fallback:abc1234567" "fallback path — must not be misframed as incremental"

echo "  PASS (12 header combinations + 4 tests-not-run × scope + all-three-signals + ordering + 2 non-'false' tests_ran + unknown-scope fail-fast + 5 worker-seam scenarios)"
